tg/tg/urls.py
# coding: utf-8

from django.conf.urls import patterns, url, include
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf import settings
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns
from tg.core.views import FacebookLogin, UserDetailsView, LoginView


admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', 'tg.core.views.index', name="index"),
    url(r'^statistics/$', 'tg.core.views.statistics', name="statistics"),

    #Municipios
    url(r'^municipios_app/', include('municipios.urls')),

    # Árvores
    
    #Lista com Todas as Árvores
    url(r'^list/tree/$', 'tg.core.views.tree_list', name="tree_list"),

    #Lista com Árvores do Usuário
    url(r'^(?P<username>\w+)/list/tree/$', 'tg.core.views.user_tree_list', name="user_tree_list"),
    url(r'^create/tree/$', 'tg.core.views.tree_create', name="tree_form"),
    url(r'^update/tree/(?P<nr_tree>\d+)/$', 'tg.core.views.tree_update', name="tree_form"),
    url(r'^detail/tree/(?P<pk>\d+)/$', 'tg.core.views.tree_detail', name="tree_detail"),
    url(r'^delete/tree/(?P<nr_tree>\d+)/$', 'tg.core.views.tree_delete', name="tree_delete"),
	
    # Autenticação e Login
    url(r'^signin/$', 'tg.core.views.signin', name='signin'),

    url(r'^login/$', 'tg.core.views.log_in', name='login'),
    
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login',
                    {'login_url': '/'}),

    url(r'', include('social_auth.urls')),

    # Admin	
    url(r'^admin/', include(admin.site.urls)),

    # Coments
    url(r'^comments/', include('fluent_comments.urls')),

    #Rest Android
    #Árvores
    url(r'^trees/$', 'tg.core.views.tree_list_android'),
    #Autenticação
    url(r'^rest-auth/', include('rest_auth.urls')),
    (r'^rest-auth/', include('rest_auth.urls')),
    (r'^rest-auth/registration/', include('rest_auth.registration.urls')),
    url(r'^rest-auth/user/logged/$', UserDetailsView.as_view(), name='rest_user_details'),
    url(r'^rest-auth/loggin/$', LoginView.as_view(), name='rest_login'),
    url(r'^rest-auth/facebook/$', FacebookLogin.as_view(), name='fb_login'),
)

urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

tg/tg/core/forms.py
# coding: utf-8

from django import forms
from tg.core.models  import Tree, Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from municipios.models import UF, Municipio

from municipios.widgets import SelectMunicipioWidget
    
# Busca por estado, cidade, bairro, endereço, espécie
# deixar opção para marcar Minhas Árvores
class SearchTreeForm(forms.Form):

    municipio = forms.IntegerField(label=u"UF - Município", widget=SelectMunicipioWidget(attrs={'style': 'width:100px'}),  required=False)
    bairro = forms.CharField(label=u"Bairro", required=False)
    endereco = forms.CharField(label=u"Endereço", required=False)
    especie = forms.CharField(label=u"Espécie", required=False)
    minhas_arvores = forms.BooleanField(label=u"Minhas Árvores", required=False)
    todas_arvores = forms.BooleanField(label=u"Todas as Árvores", required=False, initial='True')
    condicao = forms.ChoiceField(choices=Tree.COND_CHOICES_AND_EMPTY , label=u"Condição da Árvore", required=False)
    raiz = forms.TypedChoiceField(choices=Tree.RAIZ_CHOICES_AND_EMPTY, label=u"Condição das Raízes", required=False)
    luz = forms.ChoiceField(choices=Tree.LUZ_CHOICES_AND_EMPTY, label=u"Presença de Rede Elétrica", required=False)
    man = forms.ChoiceField(choices=Tree.MAN_CHOICES_AND_EMPTY, label=u"Necessidade de Manutenção", required=False)
    user = forms.CharField(label=u"Usuário", required=False)
    
    def __init__(self, *args, **kwargs):
        self.queryset = kwargs.pop('queryset', Tree.objects.all())
        super(SearchTreeForm, self).__init__(*args, **kwargs)
        

    def get_queryset(self):
        if self.is_valid():
            trees = self.queryset
            minhas_arvores = self.cleaned_data.get('minhas_arvores', False)
            user = self.cleaned_data.get('user', False)
            if minhas_arvores:
                trees = trees.filter(usuario=user)
            municipio_uf = self.cleaned_data.get('municipio_uf', False)
            if municipio_uf:
                trees = trees.filter(administrative_area_level_1=municipio_uf)
            municipio = self.cleaned_data.get('municipio', False)
            if municipio:
                trees = trees.filter(locality=municipio)
            bairro = self.cleaned_data.get('bairro', False)
            if bairro:
                trees = trees.filter(neighborhood=bairro)
            endereco = self.cleaned_data.get('endereco', False)
            if endereco:
                trees = trees.filter(route=endereco)
            especie = self.cleaned_data.get('especie', False)
            if especie:
                trees = trees.filter(especie=especie)
            condicao = self.cleaned_data.get('condicao', False)
            if condicao:
                trees = trees.filter(condicao_arvore=condicao)
            raiz = self.cleaned_data.get('raiz', False)
            if raiz:
                trees = trees.filter(condicao_raiz=raiz)
            luz = self.cleaned_data.get('luz', False)
            if luz:
                trees = trees.filter(condicao_luz=luz)
            man = self.cleaned_data.get('man', False)
            if man:
                trees = trees.filter(condicao_man=man)
            return trees
        else:
            return self.queryset

class TreeForm(forms.ModelForm):
    administrative_area_level_1 = forms.ModelChoiceField(queryset=UF.objects.all(), label="Estado")
    locality = forms.ModelChoiceField(queryset=Municipio.objects.all(), label="Municipio")
    class Meta:
        model = Tree
        widgets = {
          'descricao': forms.Textarea(attrs={'rows':1, 'cols':1, 'style': 'height: 5em;'}),
        }
        fields = ("geometry", "country", "administrative_area_level_1",
                  "locality", "neighborhood", "route", 
                  "numero", "postal_code", "point_of_interest",
                  "condicao_arvore", "especie", "altura", "condicao_raiz", 
                  "condicao_luz", "condicao_man", "descricao", "foto1", "foto2", "foto3")

class UserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = ("username", "email")

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', "password2"]:
            self.fields[fieldname].help_text = None

class ProfileForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name")
    
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        for fieldname in ['username']:
            self.fields[fieldname].help_text = None

tg/tg/core/views.py
# coding: utf-8

from django.template import RequestContext
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.core.urlresolvers import reverse_lazy, reverse

from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required

from django.contrib.comments import Comment

from django_user_agents.utils import get_user_agent
   
from django.shortcuts import render, render_to_response, get_object_or_404, redirect

from django.core.context_processors import csrf

from django.http import HttpResponse, HttpResponseBadRequest

from rest_framework.authtoken.models import Token
from rest_framework.generics import GenericAPIView
from rest_framework import viewsets
from rest_framework.renderers import JSONRenderer
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework.parsers import JSONParser, FormParser, MultiPartParser, FileUploadParser
from rest_framework.generics import RetrieveUpdateAPIView
from rest_framework.permissions import IsAuthenticated, AllowAny

from rest_auth.registration.views import SocialLoginView
from allauth.socialaccount.providers.facebook.views import FacebookOAuth2Adapter


from tg.core.models import Tree, User, Profile
from tg.core.forms import TreeForm, UserForm, ProfileForm, SearchTreeForm
from municipios.models import Municipio, UF
from tg.core.serializers import TreeSerializer, UserDetailsSerializer, LoginSerializer, TokenSerializer
from django.conf import settings

from django.contrib.auth import login, logout
from django.conf import settings

from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.authtoken.models import Token
from rest_framework.generics import RetrieveUpdateAPIView

def index(request):
    arvores = Tree.objects.all();

    if request.method == 'POST':
        form = SearchTreeForm(request.POST)
        if form.is_valid():
            condicao = form.cleaned_data['condicao']
            if condicao:
                arvores = arvores.filter(condicao_arvore=condicao)
            
            manutencao = form.cleaned_data['man']
            if manutencao:
                arvores = arvores.filter(condicao_man=manutencao)
            
            luz = form.cleaned_data['luz']
            if luz:
                arvores = arvores.filter(condicao_luz=luz)

            raiz = form.cleaned_data['raiz']
            if raiz:
                arvores = arvores.filter(condicao_raiz=raiz)
    else:
        form = SearchTreeForm()
    return render(request, 'index.html', {'search_form': form, 'arvores': arvores})

# Autenticação e Cadastro de Usuário
def signin(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        
        if form.is_valid(): 
            form.save()  
            return redirect(log_in) 
        else:
            if get_user_agent(request).is_mobile | get_user_agent(request).is_tablet:
                return render(request, "signin_mob.html", {"form": form})
            else:
                return render(request, "signin.html", {"form": form})
    if get_user_agent(request).is_mobile | get_user_agent(request).is_tablet:
        return render(request, "signin_mob.html", {"form": UserForm() })
    else:  
        return render(request, "signin.html", {"form": UserForm() })

def log_in(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST) 
        if form.is_valid():
           login(request, form.get_user())
           return redirect(index)
        else:
            if get_user_agent(request).is_mobile | get_user_agent(request).is_tablet:
                return render(request, "login_mob.html", {"form": form})
            else:
                return render(request, "login.html", {"form": form})
    if get_user_agent(request).is_mobile | get_user_agent(request).is_tablet:
        return render(request, "login_mob.html", {"form": AuthenticationForm()})
    else:
        return render(request, "login.html", {"form": AuthenticationForm()})

class StatisticsView(TemplateView):
    template_name = 'statistics.html'

    def get_context_data(self, **kwargs):
        context = super(StatisticsView, self).get_context_data(**kwargs)
        
        total_arvores = Tree.objects.all().count()

        cidades = []
        estados = []
        
        qtde_cidades = {}
        qtde_estados = {}
        
        if total_arvores != 0:

            for arvore in Tree.objects.all():

                cidades.append(arvore.locality)
                qtde_cidades = {i:cidades.count(i) for i in cidades}

                estados.append(arvore.administrative_area_level_1)
                qtde_estados = {i:estados.count(i) for i in estados}
            
            arvores_usuario = Tree.objects.filter(usuario=self.request.user).count()
            porcentagem_arvores_usuario = (arvores_usuario * 100) / total_arvores

            #arvores por condição
            arvores_boa = Tree.objects.filter(condicao_arvore='Boa - Sem sinal de praga, danos ou doenças').count()
            porcentagem_arvores_boa = (arvores_boa * 100) / total_arvores

            arvores_regular = Tree.objects.filter(condicao_arvore='Regular - Pequenos sinais de praga, danos ou doenças').count()
            porcentagem_arvores_regular = (arvores_regular * 100) / total_arvores

            arvores_ruim = Tree.objects.filter(condicao_arvore='Ruim - Risco de queda, sinal de forte ataque de pragas, doenças e danos').count()
            porcentagem_arvores_ruim = (arvores_ruim * 100) / total_arvores

            arvores_caidas = Tree.objects.filter(condicao_arvore='Caída - Árvore caída').count()
            porcentagem_arvores_caidas = (arvores_caidas * 100) / total_arvores

            #arvores por condicao de raíz
            arvores_raiz_sem = Tree.objects.filter(condicao_raiz='Não apresenta problemas - Raízes profundas e sem danos a edificações e pisos próximos').count()
            porcentagem_arvores_raiz_sem = (arvores_raiz_sem * 100) / total_arvores

            arvores_raiz_aponta = Tree.objects.filter(condicao_raiz='Aponta - Raízes superficiais, sem rachaduras, elevação ou desníveis').count()
            porcentagem_arvores_raiz_aponta = (arvores_raiz_aponta * 100) / total_arvores

            arvores_raiz_quebra = Tree.objects.filter(condicao_raiz='Quebra - Raízes  expostas, presença de algumas rachaduras').count()
            porcentagem_arvores_raiz_quebra = (arvores_raiz_quebra * 100) / total_arvores

            arvores_raiz_destroi = Tree.objects.filter(condicao_raiz='Destrói - Raízes expostas, destruição da calçada').count()
            porcentagem_arvores_raiz_destroi = (arvores_raiz_destroi * 100) / total_arvores

            #arvores por proximidade da rede elétrica
            arvores_luz_sconflito = Tree.objects.filter(condicao_luz='Presente sem conflito').count()
            porcentagem_arvores_luz_sconflito = (arvores_luz_sconflito * 100) / total_arvores

            arvores_luz_cconflito = Tree.objects.filter(condicao_luz='Presente com conflito').count()
            porcentagem_arvores_luz_cconflito = (arvores_luz_cconflito * 100) / total_arvores

            arvores_luz_ausente = Tree.objects.filter(condicao_luz='Ausente').count()
            porcentagem_arvores_luz_ausente = (arvores_luz_ausente * 100) / total_arvores

            #arvores por necessidade de manutenção
            arvores_man_sem = Tree.objects.filter(condicao_man='Sem necessidade').count()
            porcentagem_arvores_man_sem = (arvores_man_sem * 100) / total_arvores

            arvores_man_afastar = Tree.objects.filter(condicao_man='Afastar de construções').count()
            porcentagem_arvores_man_afastar = (arvores_man_afastar * 100) / total_arvores

            arvores_man_luz = Tree.objects.filter(condicao_man='Liberar Rede Elétrica').count()
            porcentagem_arvores_man_luz = (arvores_man_luz * 100) / total_arvores

            arvores_man_copa = Tree.objects.filter(condicao_man='Levantamento de copa').count()
            porcentagem_arvores_man_copa = (arvores_man_copa * 100) / total_arvores    
        else:
            arvores_usuario = 0
            porcentagem_arvores_usuario = 0

            #arvores por condição
            arvores_boa = 0
            porcentagem_arvores_boa = 0

            arvores_regular = 0
            porcentagem_arvores_regular = 0

            arvores_ruim = 0
            porcentagem_arvores_ruim = 0

            arvores_caidas = 0
            porcentagem_arvores_caidas = 0

            #arvores por condicao de raíz
            arvores_raiz_sem = 0
            porcentagem_arvores_raiz_sem = 0

            arvores_raiz_aponta = 0
            porcentagem_arvores_raiz_aponta = 0

            arvores_raiz_quebra = 0
            porcentagem_arvores_raiz_quebra = 0

            arvores_raiz_destroi = 0
            porcentagem_arvores_raiz_destroi = 0

            #arvores por proximidade da rede elétrica
            arvores_luz_sconflito = 0
            porcentagem_arvores_luz_sconflito = 0

            arvores_luz_cconflito = 0
            porcentagem_arvores_luz_cconflito = 0

            arvores_luz_ausente = 0
            porcentagem_arvores_luz_ausente = 0

            #arvores por necessidade de manutenção
            arvores_man_sem = 0
            porcentagem_arvores_man_sem = 0

            arvores_man_afastar = 0
            porcentagem_arvores_man_afastar = 0

tg/tg/core/templates/index.html
{% extends "base.html" %}

{% load staticfiles %}
{% load bootstrap %}
{% load user_agents %}

{% block title %} {% endblock %}

{% block content %}

  <link href="{% static 'css/map.css' %}" rel="stylesheet" />

  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  
  <div id="mapa_tree_list"> <!-- Mapa -->
    
  </div>
  <div id="scale-line" class="scale-line"></div>

  <div>
    {% if not request.user_agent.is_mobile and not request.user_agent.is_tablet %}
    <a id="localize" href="" onclick="getLocation()"><i class="fa fa-compass fa-5x"></i></a>

    <!-- Trigger the modal FILTRAR with a button -->
     <button type="button" id="filtro" class="btn btn-primary" data-toggle="modal" data-target="#fModal"><span class="glyphicon glyphicon-map-marker"></span> FILTRAR </button>
    {% endif %}

     <!-- Trigger the modal LEGENDA with a button -->
    <button type="button" id="legenda" class="btn btn-primary" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-map-marker"></span> LEGENDA</button>

  </div>

    <!-- Modal do Filtro -->
  <div class="modal fade" id="fModal" align="center" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">FILTRAR<br><small>Selecione as opções para filtrar visualização</small></h4>
        </div>
        <div class="modal-body" align="left">
          <form method="POST">
            {% csrf_token %}
          
            {{ search_form.condicao | bootstrap }}
            {{ search_form.man | bootstrap }}
            {{ search_form.luz | bootstrap }}
            {{ search_form.raiz | bootstrap }}
          <div align="center">
          <button type="submit"  class="btn btn-default">
            <span class="glyphicon glyphicon-search"></span> Pesquisar </button>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

          <button class="btn btn-default" type="button" onclick="limpa_pesquisa();" >
                            <span class="glyphicon glyphicon-remove"></span>
                            &nbsp; Limpar  &nbsp;
                          </button>
          </div>
          </form>
        </div>
        
      </div>
      
    </div>
  </div>

  <!-- Modal da Legenda -->
  <div class="modal fade" id="myModal"  align="center" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content responsive">
        
        <div class="modal-body" align="left">
          <h4 class="modal-title">LEGENDA <br><small>As árvores são mostradas no mapa de acordo com sua condição</small></h4><br>
          <img src="/static/img/icons/tree_good.png"> Boa - Sem sinal de praga, danos ou doenças 
          <br>
          <img src="/static/img/icons/tree_regular.png"> Regular - Pequenos sinais de praga, danos ou doenças 
          <br>
          <img src="/static/img/icons/tree_bad.png"> Ruim - Risco de queda, sinal de forte ataque de pragas, doenças e danos 
         <br>
         <img src="/static/img/icons/down.png"> Caída - Árvore caída 
        </div>
        <div align="center">
          <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        </div>
        <br>
      </div>
      
    </div>

<!-- JavaScript Mapa -->
  <script src="{% static 'openlayers/OpenLayers.js' %}"></script> 
  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>  


  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>  

  <script type="text/javascript">
    
  //função para limpar selects do filtro
  function limpa_pesquisa(){
    $("#id_condicao").val("");
    $("#id_man").val("");
    $("#id_luz").val("");
    $("#id_raiz").val("");
  };
  //fim da função

    $( document ).ready(function() {
      getLocation();
    
    });   

      //função para encontrar localização do usuário (shared location - Google)
  function getLocation() {
    var geolocation_support = document.getElementById("d");
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(showPosition);
    } else { 
      geolocation_support.innerHTML = "Geolocation is not supported by this browser.";
    }
  };

  //função para marcar (add ícone) posição no mapa e chama função para buscar endereço com as coordenadas (getLocation - Google)
  function showPosition(position) {
    var lonlat = new OpenLayers.LonLat(position.coords.longitude, position.coords.latitude)
    lonlat.transform(
      new OpenLayers.Projection("EPSG:4326"), // transform from WGS 1984
      map.getProjectionObject() // to Spherical Mercator Projection
    );

    map.setCenter (lonlat, 15);
  };
  //fim das funções

    map = new OpenLayers.Map("mapa_tree_list");
    map.addLayer(new OpenLayers.Layer.OSM());
    
    var scaleline = new OpenLayers.Control.ScaleLine();
    map.addControl(scaleline);


    epsg4326 =  new OpenLayers.Projection("EPSG:4326"); //WGS 1984 projection
    projectTo = map.getProjectionObject(); //The map projection (Spherical Mercator)
   
    var lonLat = new OpenLayers.LonLat( -47.5356, -18.2246).transform(epsg4326, projectTo);
          
    var zoom=5;
    
    var markers = new Array();
    map.setCenter (lonLat, zoom);

    var vectorLayer = new OpenLayers.Layer.Vector("VectorPoints");

    {% for arvore in arvores %}

      var lat1 = String([{{ arvore.geometry.x }}]);
      var lat = lat1.replace(",", ".")

      var lon1 = String([{{ arvore.geometry.y }}]);
      var lon = lon1.replace(",", ".")
      var endereco = "{{arvore.administrative_area_level_1}}, {{arvore.locality}}{% if not arvore.neighborhood or arvore.neighborhood == ' ' %}{% else %},<br/>{{arvore.neighborhood}}{% endif %}{% if not arvore.route or arvore.route == ' '%}{% else %}, {{arvore.route}}{% endif %}, {{arvore.numero}}{% if not arvore.postal_code or arvore.postal_code == ' ' %}{% else %}, {{arvore.postal_code}} {% endif %}";
      var especie = "{% if not arvore.especie or arvore.especie == ' ' %}Espécie não informada{% else %}{{arvore.especie}}{% endif %}";
      markers.push([especie, lon, lat, endereco]);
    
    {% endfor %}
    
    var i = 0;
    {% for arvore in arvores %}

      var lon = markers[i][1];
      var lat = markers[i][2];      

      var feature = new OpenLayers.Feature.Vector(
        new OpenLayers.Geometry.Point( lon, lat ).transform(epsg4326, projectTo),
          {description: "<div style='text-align:right'>" +  
            "<div style='text-align:left'><b>Espécie: </b>" + markers[i][0] + "<br/><br/><b>Endereço: </b>" + markers[i][3] + 
            "</div>" + 
          "<div align='right'><br><a id='detail' class='btn btn-success' href='{% url 'tree_detail' arvore.pk %}'><span class='glyphicon glyphicon-plus'></span> Detalhes</a></div>"},

            {% if arvore.condicao_arvore == 'Boa - Sem sinal de praga, danos ou doenças' or arvore.condicao_arvore == 'Boa' %}

            {externalGraphic: '/static/img/icons/tree_good.png', graphicHeight: 36, graphicWidth: 32, graphicXOffset:-22, graphicYOffset:-36}

            {% elif arvore.condicao_arvore == 'Regular - Pequenos sinais de praga, danos ou doenças' or arvore.condicao_arvore == 'Regular' %}
             {externalGraphic: '/static/img/icons/tree_regular.png', graphicHeight: 36, graphicWidth: 32,  graphicXOffset:-12, graphicYOffset:-26}
             {% elif arvore.condicao_arvore == 'Ruim - Risco de queda, sinal de forte ataque de pragas, doenças e danos' or arvore.condicao_arvore == 'Ruim'%}
             {externalGraphic: '/static/img/icons/tree_bad.png', graphicHeight: 36, graphicWidth: 32, graphicXOffset:-22, graphicYOffset:-36}
             {% elif arvore.condicao_arvore == 'Caída - Árvore caída' or arvore.condicao_arvore == 'Caída' %}
             {externalGraphic: '/static/img/icons/down.png', graphicHeight: 36, graphicWidth: 32, graphicXOffset:-12, graphicYOffset:-26}
           {% endif %}
      );             

      vectorLayer.addFeatures(feature);
      i+= 1;
    {% endfor %} // fim do for   

    map.addLayer(vectorLayer);

    //Add popup
    var controls = {
      selector: new OpenLayers.Control.SelectFeature(vectorLayer, 
        { onSelect: createPopup, onUnselect: destroyPopup })
    };
   
    function createPopup(feature) {
      feature.popup = new OpenLayers.Popup.FramedCloud("popup",
        feature.geometry.getBounds().getCenterLonLat(),
        null,
        '<div class="markerContent">'+feature.attributes.description+'</div>',
        null,
        true,
        function() { controls['selector'].unselectAll(); 
    });
  
    //feature.popup.closeOnMove = true;
    map.addPopup(feature.popup);
    }

    function destroyPopup(feature) {
      feature.popup.destroy();
      feature.popup = null;
    }
    
    map.addControl(controls['selector']);
    controls['selector'].activate();




</script>          
  </div>
{% endblock content %}

tg/tg/core/templates/signin.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %} | Registrar {% endblock %}

{% block content %}
  <link href="http://fonts.googleapis.com/css?family=Lato:100italic,100,300italic,300,400italic,400,700italic,700,900italic,900" rel="stylesheet" type="text/css">

  <link href="{% static 'css/signin.css' %}" rel="stylesheet" />

  <section class="container login-form">
    <section>

      <form method="POST" action="" role="login">
         {% csrf_token %}
        <img src="/static/img/logo.png" alt="" style="width:60%;" class="img-responsive" />
        
        <div class="form-group">
          {{ form.username.errors }}
          {{ form.username }}
        </div>

        <div class="form-group">
          {{ form.email.errors }}
          {{ form.email }}
        </div>
        
        <div class="form-group">
          {{ form.password1.errors }}
          {{ form.password1 }}
        </div>

        <div class="form-group">
          {{ form.password2.errors }}
          {{ form.password2 }}
        </div>
        
        <button type="submit" name="go" class="btn btn-primary btn-block">Registrar</button>
        <a class="btn btn-social btn-google" id="google" href="{% url 'socialauth_begin' 'google-oauth2' %}">
                <i class="fa fa-google-plus-square"></i> 
                Acesse com o Google
        </a>
              
        &nbsp;&nbsp;&nbsp;  
        <a class="btn btn-social btn-facebook" id="facebook" href="{% url 'socialauth_begin' 'facebook' %}">
          <i class="fa fa-facebook-square"></i> 
            Acesse com o Facebook
        </a>
      </form>

    </section>
  </section>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  
<script type="text/javascript" >
    $(document).ready(function(){
        $("#id_username").attr('placeholder', '  {{form.username.label}} ');
        $("#id_email").attr('placeholder', '  {{form.email.label}} ');
        $("#id_password1").attr('placeholder', '  {{form.password1.label}} ');
        $("#id_password2").attr('placeholder', '  {{form.password2.label}} ');
    });
</script>

 
{% endblock content %}